version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    command: flask db upgrade
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development

  init-script:
    build: .
    depends_on:
      - migrate
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c "
      while ! pg_isready -h db -U postgres; do
        sleep 1;
      done;
      sleep 10;
      psql -h db -U postgres -d postgres -f /app/init.sql"

  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - init-script
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development
      - SECRET_KEY=uerguerhgiuoehgeurih

volumes:
  postgres_data:
