services:
  web:
    image: leovzdc/web:latest  # Specify the image from Docker Hub
    environment:
      - AWS_ACCESS_KEY_ID=AKIA5H7J64PHPBTYTBH4

      - DATABASE_URL=postgresql://postgres:postgres@192.168.0.18:5432/MKLv0.2
    ports:
      - "5000:5000"  # Map the container's port to your host's port
    volumes:
      - ./data:/app/data  # Mount local directories or files if needed
    restart: always  # Optional: Restart policy