"""Description of your migration

Revision ID: 17326db448b4
Revises: 
Create Date: 2024-07-30 23:52:53.268731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17326db448b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('TeamID', sa.Integer(), nullable=False),
    sa.Column('TeamName', sa.String(length=100), nullable=True),
    sa.Column('Abbreviation', sa.String(length=10), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('CoachName', sa.String(length=100), nullable=True),
    sa.Column('AssistantCoachName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('TeamID')
    )
    op.create_table('games',
    sa.Column('GameID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(length=50), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('HomeTeamID', sa.Integer(), nullable=True),
    sa.Column('AwayTeamID', sa.Integer(), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AwayTeamID'], ['teams.TeamID'], ),
    sa.ForeignKeyConstraint(['HomeTeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('GameID')
    )
    op.create_table('players',
    sa.Column('PlayerID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('TeamID', sa.Integer(), nullable=True),
    sa.Column('Position', sa.String(length=50), nullable=True),
    sa.Column('Shoots', sa.String(length=10), nullable=True),
    sa.Column('Height', sa.String(length=20), nullable=True),
    sa.Column('Weight', sa.Integer(), nullable=True),
    sa.Column('BirthDate', sa.String(length=50), nullable=True),
    sa.Column('BirthCity', sa.String(length=100), nullable=True),
    sa.Column('BirthCountry', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['TeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('PlayerID')
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(50), nullable=False, unique=True),
        sa.Column('email', sa.String(120), nullable=False, unique=True),
        sa.Column('password', sa.String(200), nullable=False),
        sa.Column('role', sa.String(50), nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('teams')
    # ### end Alembic commands ###
