"""empty message

Revision ID: 1dc54fc52f8e
Revises: 7c563e3b8f78
Create Date: 2024-08-20 12:32:40.928838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc54fc52f8e'
down_revision = '7c563e3b8f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clock', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('clock')
        batch_op.drop_column('period')
        batch_op.drop_column('away_score')
        batch_op.drop_column('home_score')

    # ### end Alembic commands ###
