"""draft table

Revision ID: 3da917c729a1
Revises: bbeaa6bbeb09
Create Date: 2024-08-11 13:39:13.803321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da917c729a1'
down_revision = 'bbeaa6bbeb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_staff_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.GameID'], ),
    sa.ForeignKeyConstraint(['position_id'], ['staff_positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture_staff_draft')
    # ### end Alembic commands ###
