"""empty message

Revision ID: 6b9b633cbb60
Revises: 4d34670b7969
Create Date: 2024-08-21 16:16:49.249660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9b633cbb60'
down_revision = '4d34670b7969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_sog', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team_sog', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game', schema=None) as batch_op:
        batch_op.drop_column('away_team_sog')
        batch_op.drop_column('home_team_sog')

    # ### end Alembic commands ###
