"""empty message

Revision ID: 7c563e3b8f78
Revises: 
Create Date: 2024-08-12 23:01:31.617566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c563e3b8f78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('TeamID', sa.Integer(), nullable=False),
    sa.Column('TeamName', sa.String(length=100), nullable=True),
    sa.Column('Abbreviation', sa.String(length=10), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('CoachName', sa.String(length=100), nullable=True),
    sa.Column('AssistantCoachName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('TeamID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('GameID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(length=50), nullable=True),
    sa.Column('EndTime', sa.String(length=50), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('HomeTeamID', sa.Integer(), nullable=True),
    sa.Column('AwayTeamID', sa.Integer(), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AwayTeamID'], ['teams.TeamID'], ),
    sa.ForeignKeyConstraint(['HomeTeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('GameID')
    )
    op.create_table('players',
    sa.Column('PlayerID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('TeamID', sa.Integer(), nullable=True),
    sa.Column('Position', sa.String(length=50), nullable=True),
    sa.Column('Shoots', sa.String(length=10), nullable=True),
    sa.Column('Height', sa.String(length=20), nullable=True),
    sa.Column('Weight', sa.Integer(), nullable=True),
    sa.Column('BirthDate', sa.String(length=50), nullable=True),
    sa.Column('BirthCity', sa.String(length=100), nullable=True),
    sa.Column('BirthCountry', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['TeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('PlayerID')
    )
    op.create_table('fixture_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.GameID'], ),
    sa.ForeignKeyConstraint(['position_id'], ['staff_positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_staff_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.GameID'], ),
    sa.ForeignKeyConstraint(['position_id'], ['staff_positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_sog', sa.Integer(), nullable=True),
    sa.Column('away_sog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.GameID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.GameID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_availability')
    op.drop_table('game_stats')
    op.drop_table('fixture_staff_draft')
    op.drop_table('fixture_staff')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('user')
    op.drop_table('teams')
    op.drop_table('staff_positions')
    # ### end Alembic commands ###
