"""Fixtures model

Revision ID: a7972207163c
Revises: 17326db448b4
Create Date: 2024-07-31 13:32:25.123851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7972207163c'
down_revision = '17326db448b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('GameID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(length=50), nullable=True),
    sa.Column('EndTime', sa.String(length=50), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('HomeTeamID', sa.Integer(), nullable=True),
    sa.Column('AwayTeamID', sa.Integer(), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AwayTeamID'], ['teams.TeamID'], ),
    sa.ForeignKeyConstraint(['HomeTeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('GameID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
