"""empty message

Revision ID: bbeaa6bbeb09
Revises: d9f9d2f78b72
Create Date: 2024-08-11 12:46:01.711270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeaa6bbeb09'
down_revision = 'd9f9d2f78b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_staff', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
